import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Disclaimer | AutoBrief",
  description: "Content disclaimer for AutoBrief — AI-generated news summaries for informational purposes only.",
}

export default function DisclaimerPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <h1 className="text-3xl font-bold text-foreground mb-2">Disclaimer</h1>
        <p className="text-sm text-muted-foreground mb-10">Last updated: June 2026</p>

        <div className="space-y-8 text-sm text-muted-foreground leading-relaxed">

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">General Disclaimer</h2>
            <p>
              AutoBrief is an automated news aggregation platform. All articles are AI-generated
              summaries of publicly available RSS content and are provided for informational
              purposes only. AutoBrief is not a news organisation, does not employ journalists,
              and does not produce original reporting.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">Accuracy of Content</h2>
            <p>
              While AutoBrief uses AI to summarise news content, errors, omissions, or inaccuracies
              may exist. Content may be outdated by the time you read it. We strongly encourage
              users to verify any important information with the original source before acting on it.
              AutoBrief accepts no liability for decisions made based on content published on this
              platform.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">AI-Generated Content</h2>
            <p>
              Articles on AutoBrief are generated by large language models (LLMs). AI can make
              mistakes, hallucinate facts, or misrepresent nuance. AutoBrief does not guarantee
              that AI-generated summaries faithfully represent the original source material in
              every detail.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">No Professional Advice</h2>
            <p>
              Nothing on AutoBrief constitutes legal, financial, medical, or professional advice.
              Do not make professional or personal decisions based solely on content from this
              platform. Always consult a qualified professional.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">No Affiliation</h2>
            <p>
              AutoBrief is not affiliated with, endorsed by, or partnered with any of the news
              organisations whose RSS feeds are aggregated. All trademarks and brand names belong
              to their respective owners.
            </p>
          </section>

          <section>
            <h2 className="text-base font-semibold text-foreground mb-3">Limitation of Liability</h2>
            <p>
              AutoBrief and its creator shall not be held liable for any loss, damage, or harm
              resulting from use of this platform or reliance on its content. The platform is
              provided "as is" without any warranties of any kind.
            </p>
          </section>

        </div>
      </div>
    </div>
  )
}
